/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bank_management_system;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author Kusal Saraf
 */
public class fundtransfer extends javax.swing.JFrame {

	/**
	 * Creates new form fundtransfer
	 */
	public fundtransfer() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
        
		jLabel1 = new JLabel();
		jLabel2 = new JLabel();
		jTextField1 = new JTextField();
		jTextField2 = new JTextField();
		jButton1 = new JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("FundTransfer");
		jLabel1.setText("Account Number");
		jLabel1.setFont(new Font("HP Simplified", Font.BOLD, 16));
		jLabel2.setText("Amount ");
		jLabel2.setFont(new Font("HP Simplified", Font.BOLD, 16));

		jTextField1.setFont(new Font("Tahoma", 1, 14)); // NOI18N
		jTextField1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});
		jTextField1.addKeyListener(new KeyAdapter() {
			public void keyPressed(KeyEvent evt) {
				jTextField1KeyPressed(evt);
			}
		});

		jTextField2.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
		jTextField2.addKeyListener(new KeyAdapter() {
			public void keyPressed(KeyEvent evt) {
				jTextField2KeyPressed(evt);
			}
		});

		jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
		jButton1.setText(" Send  ");
		jButton1.setBackground(Color.green);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		getContentPane().setBackground(new Color(122,180,25));
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addGap(24, 24, 24)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
						.addGap(26, 26, 26)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jTextField1)
								.addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
						.addGroup(layout.createSequentialGroup().addGap(116, 116, 116).addComponent(jButton1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(114, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(101, 101, 101)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(42, 42, 42).addComponent(jButton1).addContainerGap(62, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField1KeyPressed
		// TODO add your handling code here:
		char c = evt.getKeyChar();
		if (Character.isLetter(c)) {
			jTextField1.setEditable(false);
		} else {
			jTextField1.setEditable(true);
		}
	}// GEN-LAST:event_jTextField1KeyPressed

	private void jTextField2KeyPressed(KeyEvent evt) {// GEN-FIRST:event_jTextField2KeyPressed
		// TODO add your handling code here:
		char c = evt.getKeyChar();
		if (Character.isLetter(c)) {
			jTextField1.setEditable(false);
		} else {
			jTextField1.setEditable(true);
		}
	}// GEN-LAST:event_jTextField2KeyPressed

	private void jButton1ActionPerformed(ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		if (jTextField1.getText().isEmpty()) {
			JOptionPane.showMessageDialog(fundtransfer.this, "Enter the account number");
			jTextField1.grabFocus();
			return;
		}
		if (jTextField2.getText().isEmpty()) {
			JOptionPane.showMessageDialog(fundtransfer.this, "Enter the amount");
			jTextField2.grabFocus();
			return;
		}
		Methods obj = new Methods();
		if (obj.accExist(jTextField1.getText())) {
			if (obj.balChk(Long.parseLong(jTextField2.getText()))) {
				obj.transferBalance(jTextField1.getText(), Long.parseLong(jTextField2.getText()));
				JOptionPane.showMessageDialog(fundtransfer.this, "Sent successfullt");
				this.setVisible(false);
			} else {
				JOptionPane.showMessageDialog(fundtransfer.this, "Insufficient Balance");
			}
		} else {
			JOptionPane.showMessageDialog(fundtransfer.this, "Invalid account number");
		}

	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(fundtransfer.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(fundtransfer.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(fundtransfer.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(fundtransfer.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new fundtransfer().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton jButton1;
	private JLabel jLabel1;
	private JLabel jLabel2;
	
	private JTextField jTextField1;
	private JTextField jTextField2;
	// End of variables declaration//GEN-END:variables
}
