
package com.mycompany.bank_management_system;

import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.awt.color.*;

/**
 *
 * @author Kusal Saraf & Buddhadeb Garai
 */
public class MainUI extends javax.swing.JFrame {
	int i = 2;

	/**
	 * Creates new form MainUI
	 */
	public MainUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel2 = new JLabel();

		jLabel1 = new JLabel();
		jLabel3 = new JLabel();
		jTextField1 = new JTextField();
		jButton1 = new JButton();
		jPasswordField1 = new JPasswordField();
		jButton2 = new JButton();
		jButton3 = new JButton();
		jButton4 = new JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Bank Management system");

		jLabel2.setText(" User Login");
		jLabel2.setForeground(Color.white);
		jLabel2.setFont(new Font("HP Simplified", Font.BOLD, 24));
		// jLabel1.setBounds(10, 75,100, 24);// NOI18N

		jLabel1.setFont(new Font("Trebuchet MS", Font.BOLD, 16)); // NOI18N
		jLabel1.setText("Username");
		jLabel1.setForeground(Color.white);

		jLabel3.setFont(new Font("Trebuchet MS", Font.BOLD, 16)); // NOI18N
		jLabel3.setText("Password");
		jLabel3.setForeground(Color.white);

		jTextField1.setFont(new Font("Tahoma", Font.PLAIN, 12)); // NOI18N
		jTextField1.setToolTipText("");
		jTextField1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("Log in");
        jButton1.setBackground(Color.orange);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jPasswordField1.setFont(new Font("Trebuchet MS", 1, 14)); // NOI18N

		jButton2.setFont(new java.awt.Font("Trebuchet MS", Font.ROMAN_BASELINE + Font.BOLD, 15)); // NOI18N
		jButton2.setText("New User");
		jButton2.setBackground(Color.green);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setFont(new java.awt.Font("Tahoma", Font.ROMAN_BASELINE + Font.BOLD, 15)); // NOI18N
		jButton3.setText("Forgot password");
		jButton3.setBackground(Color.orange);
		jButton3.setForeground(Color.red);
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButton4.setText("Database");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		getContentPane().setBackground(new Color(45,40,75));
		layout.setHorizontalGroup(layout
				.createParallelGroup(
						GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(160, 160, 160)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
										.addComponent(
												jButton2, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
										.addGap(120, 120, 120)
										.addGroup(layout
												.createParallelGroup(GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1).addComponent(jLabel3)))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addGap(25, 25, 25).addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 136,
														Short.MAX_VALUE)
												.addComponent(jPasswordField1)))
										.addGroup(layout.createSequentialGroup().addGap(120, 120, 120)
												.addComponent(jButton3))))
						.addGroup(layout.createSequentialGroup().addGap(300, 300, 300).addComponent(jButton1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(281, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(350, 350, 350))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(46, 46, 46)))));
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(30, 30, 30)
				.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE).addGap(5, 5, 5)
				.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE).addGap(44, 44, 44)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(
						jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(30, 30, 30)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jLabel3).addComponent(
						jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
						GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
						.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addContainerGap(19, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		try {
		if (jTextField1.getText().isEmpty()) {
			JOptionPane.showMessageDialog(MainUI.this, "Enter your username");
			jTextField1.grabFocus();
			return;
		}
		if (jPasswordField1.getText().isEmpty()) {
			JOptionPane.showMessageDialog(MainUI.this, "Enter your password");
			jPasswordField1.grabFocus();
			return;
		}
		String username = jTextField1.getText();
		String password = jPasswordField1.getText();
		Methods obj = new Methods();
		boolean flag;
		if (obj.checkLoginDetails(username, password) && Methods.obj.getActivation().equals("1")) {
			JOptionPane.showMessageDialog(MainUI.this, "Sucessfully logged in");
			this.setVisible(false);
			User obj2 = new User();
			obj2.setVisible(true);

		} else {
			Methods obj1 = new Methods();
			//System.out.print(obj1.validUser(username));
			if (obj1.checkFreez(username)) {
				JOptionPane.showMessageDialog(MainUI.this, "Account have been freez");
				this.setVisible(false);
			}
			
			else if(obj1.validUser(username)){
				//System.out.print(obj1.accExist(username));
				JOptionPane.showMessageDialog(MainUI.this, "Invalid Username/Password chance remaining " + i);
				i = i - 1;
				if (i == -1) {

					flag = obj1.freezAcc(jTextField1.getText());
					if (flag) {
						JOptionPane.showMessageDialog(MainUI.this, "Your account have been freez");
						this.setVisible(false);
					} else {
						JOptionPane.showMessageDialog(MainUI.this, "Your have tried maximum time exiting");
						this.setVisible(false);
					}
				}
			}
			else 
			{
				JOptionPane.showMessageDialog(MainUI.this, "Account not found");
			}
			jTextField1.setText("");
			jPasswordField1.setText("");
		}
		}
		catch(Exception e)
		{
			System.out.println(e.toString());
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		newuser obj6 = new newuser();
		obj6.setVisible(true);
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
		resetpassword rs = new resetpassword();
		rs.setVisible(true);
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:
		dbPassword obj7 = new dbPassword();
		obj7.setVisible(true);
	}// GEN-LAST:event_jButton4ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables
}
